### ISSUE TITLE
We have found a regression introduced between 5.1.1 and 5.1.3.

### ISSUE THREAD

**Issue by oliviertassinari** [brigand/babel-plugin-flow-react-proptypes#132]
Here is the falling case: https://github.com/callemall/material-ui/pull/8206

> Error: src/styles/MuiThemeProvider.js: Did not find type annotation for MuiThemeProvider
    at annotate (/tmp/material-ui/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:89:13)
    at PluginPass.ClassDeclaration (/tmp/material-ui/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:202:18)
    at NodePath._call (/tmp/material-ui/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/tmp/material-ui/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/tmp/material-ui/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/tmp/material-ui/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/tmp/material-ui/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/tmp/material-ui/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/tmp/material-ui/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/tmp/material-ui/node_modules/babel-traverse/lib/path/context.js:115:19)

It's most likely coming from 5.1.2. Is [the failing build](https://circleci.com/gh/callemall/material-ui/8202?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) enough? Otherwise, I can work on simplifying the reproduction.

**Comment by brigand** [comment]
Thanks for the report. Fixed in 5.1.4.

The issue was `React.Component<Object>` where it didn't know about `Object`. New behavior is to not generate any propTypes in that case.

**Comment by oliviertassinari** [comment]
@brigand Thanks a lot!
