### ISSUE TITLE
Flow 0.53.0 Component Annotations Break When Importing Props

### ISSUE THREAD

**Issue by robwise** [brigand/babel-plugin-flow-react-proptypes#133]
Hi, thanks for this plugin, been using it for 1.5 years now! I'm bumping flow on my project (was pre-0.53.0), but I'm getting an issue in these weird cases where we've had to import the props from a different file and are using the new class annotations.

```js
// file1 that defines props
export type Props = { favoriteFruit: 'apple' };

// file2 that defines component
import React from 'react';
import type { Props } from './file1';

type State = {};

class MyComponent extends React.Component<Props, State> { ... }
```

This throws when compiling:

<details> 
```
[CLIENT_BUNDLES] Module build failed: Error: /Users/rob/dev/friendsandguests/client/app/bundles/listings-show/ui/Listing/Summary/edit/FormState.jsx: Did not find type annotation for SummaryFormState
[CLIENT_BUNDLES]     at annotate (/Users/rob/dev/friendsandguests/client/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:89:13)
[CLIENT_BUNDLES]     at PluginPass.ClassDeclaration (/Users/rob/dev/friendsandguests/client/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:203:18)
[CLIENT_BUNDLES]     at newFn (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/visitors.js:276:21)
[CLIENT_BUNDLES]     at NodePath._call (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/path/context.js:76:18)
[CLIENT_BUNDLES]     at NodePath.call (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/path/context.js:48:17)
[CLIENT_BUNDLES]     at NodePath.visit (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/path/context.js:105:12)
[CLIENT_BUNDLES]     at TraversalContext.visitQueue (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:150:16)
[CLIENT_BUNDLES]     at TraversalContext.visitQueue (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:156:21)
[CLIENT_BUNDLES]     at TraversalContext.visitMultiple (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:103:17)
[CLIENT_BUNDLES]     at TraversalContext.visit (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:190:19)
[CLIENT_BUNDLES]     at Function.traverse.node (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/index.js:114:17)
[CLIENT_BUNDLES]     at NodePath.visit (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/path/context.js:115:19)
[CLIENT_BUNDLES]     at TraversalContext.visitQueue (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:150:16)
[CLIENT_BUNDLES]     at TraversalContext.visitSingle (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:108:19)
[CLIENT_BUNDLES]     at TraversalContext.visit (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/context.js:192:19)
[CLIENT_BUNDLES]     at Function.traverse.node (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/index.js:114:17)
[CLIENT_BUNDLES]     at traverse (/Users/rob/dev/friendsandguests/client/node_modules/babel-traverse/lib/index.js:79:12)
[CLIENT_BUNDLES]     at File.transform (/Users/rob/dev/friendsandguests/client/node_modules/babel-core/lib/transformation/file/index.js:548:35)
[CLIENT_BUNDLES]     at /Users/rob/dev/friendsandguests/client/node_modules/babel-core/lib/transformation/pipeline.js:50:19
[CLIENT_BUNDLES]     at File.wrap (/Users/rob/dev/friendsandguests/client/node_modules/babel-core/lib/transformation/file/index.js:564:16)
[CLIENT_BUNDLES]
[CLIENT_BUNDLES]     at Pipeline.transform (/Users/rob/dev/friendsandguests/client/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
[CLIENT_BUNDLES]     at transpile (/Users/rob/dev/friendsandguests/client/node_modules/babel-loader/lib/index.js:50:20)
[CLIENT_BUNDLES]     at /Users/rob/dev/friendsandguests/client/node_modules/babel-loader/lib/fs-cache.js:118:18
[CLIENT_BUNDLES]     at ReadFileContext.callback (/Users/rob/dev/friendsandguests/client/node_modules/babel-loader/lib/fs-cache.js:31:21)
[CLIENT_BUNDLES]     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:421:13)
```
</details>

(This is on version 5.1.4, with flow 0.54.0)

**Comment by robwise** [comment]
Wow, amazing!
