### ISSUE TITLE
Issues with non-props files

### ISSUE THREAD

**Issue by ericwooley** [brigand/babel-plugin-flow-react-proptypes#15]
First off, thanks for this project! I really hope to get it working soon!

I have a project with flow all over the place, not just in react components. Adding this to my babel plugins give me this error.
```bash
ERROR in ./src/redux/modules/auth.js
Module build failed: Error: /Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/src/redux/modules/auth.js: babel-plugin-flow-react-proptypes: Encountered an unknown node in the type definition. Node: {"type":"NullableTypeAnnotation","start":2551,"end":2560,"loc":{"start":{"line":81,"column":35},"end":{"line":81,"column":44}},"typeAnnotation":{"type":"GenericTypeAnnotation","start":2552,"end":2560,"loc":{"start":{"line":81,"column":36},"end":{"line":81,"column":44}},"typeParameters":null,"id":{"type":"Identifier","start":2552,"end":2560,"loc":{"start":{"line":81,"column":36},"end":{"line":81,"column":44}},"name":"Employee"}}}
    at convertToPropTypes (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:64:11)
    at /Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:20:15
    at Array.map (native)
    at convertToPropTypes (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:15:31)
    at PluginPass.ExportNamedDeclaration (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:85:58)
    at newFn (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:135:17)
    at Object.traverse [as default] (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:69:12)
 @ ./src/redux/rootReducer.js 13:12-37
```
Here is the offending file (auth.js)
```js
/* @flow */
import {login} from 'api/auth-api'
import {setShopsAction, setAssignedShop} from './shops'
import Employee from 'models/employee'
import {setToken, clearToken} from './headers'
// ------------------------------------
// Constants
// ------------------------------------
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
// ------------------------------------
// Actions
// ------------------------------------
// NOTE: "Action" is a Flow interface defined in https://github.com/TechnologyAdvice/flow-interfaces
// If you're unfamiliar with Flow, you are completely welcome to avoid annotating your code, but
// if you'd like to learn more you can check out: flowtype.org.
export const loginAction = ({employee, loginTime, company}: Object): Action => ({
  // employee: string, loginTime: number, company: string
  type: LOGIN,
  payload: {employee: employee, loginTime, company}
})

export const logoutAction = (): Action => ({
  // employee: string, loginTime: number, company: string
  type: LOGOUT
})

// function total (numbers: Array<number>) {
//   numbers.reduce((total: number, item: number) => {
//     return total + item
//   }, 0)
// }
//
// total(['test'])

// This is a thunk, meaning it is a function that immediately
// returns a function for lazy evaluation. It is incredibly useful for
// creating async actions, especially when combined with redux-thunk!
// NOTE: This is solely for demonstration purposes. In a real application,
// you'd probably want to dispatch an action of COUNTER_DOUBLE and let the
// reducer take care of this logic.

export const requestLogin = (email: string, password: string): Function => {
  return (dispatch: Function, getState: Function): Promise => {
    return login(email, password)
      .then((response) => {
        dispatchLoginResponseActions(dispatch, response)
        return response
      })
  }
}

export const logout = (): Function => {
  return (dispatch) => {
    return new Promise((resolve) => {
      dispatch(clearToken())
      dispatch(logoutAction())
      resolve()
    })
  }
}

function dispatchLoginResponseActions (dispatch, response) {
  dispatch(setToken(response.accessToken))
  dispatch(loginAction(response))
  dispatch(setShopsAction(response.shops))
  if (response.assignedShop) {
    dispatch(setAssignedShop(response.assignedShop))
  }
}

export const actions = {
  loginAction,
  requestLogin,
  logout
}

// ------------------------------------
// Action Handlers
// ------------------------------------
export type AuthState = {employee: ?Employee, loginTime: ?number, company: ?Object}

const initialState: AuthState = {employee: null, loginTime: null, company: null}
const ACTION_HANDLERS = {
  [LOGIN]: (state: Object, action): Object => ({...state, ...action.payload}),
  [LOGOUT]: () => initialState
}

// ------------------------------------
// Reducer
// ------------------------------------

export default function authReducer (state: AuthState = initialState, action: Action): AuthState {
  const handler = ACTION_HANDLERS[action.type]
  return handler ? handler(state, action) : state
}
```
and the webpack/babel config
```js
webpackConfig.module.loaders = [{
  test: /\.(js|jsx)$/,
  exclude: /node_modules/,
  loader: 'babel',
  query: {
    cacheDirectory: true,
    plugins: ['transform-runtime', 'transform-decorators-legacy'],
    presets: ['es2015', 'react', 'stage-0'],
    env: {
      development: {
        plugins: [
          'transform-decorators-legacy',
          'flow-react-proptypes',
          ['react-transform', {
            transforms: [{
              transform: 'react-transform-hmr',
              imports: ['react'],
              locals: ['module']
            }, {
              transform: 'react-transform-catch-errors',
              imports: ['react', 'redbox-react']
            }]
          }]
        ]
      },
      production: {
        plugins: [
          'transform-react-remove-prop-types',
          'transform-react-constant-elements'
        ]
      }
    }
  }
},
{
  test: /\.json$/,
  loader: 'json'
}]
```

**Comment by brigand** [comment]
Thanks for reporting!

Let me know if the new version fixes the problem for you.

**Comment by ericwooley** [comment]
Thanks for the quick response. That got rid of almost all the errors in a lot of files! Thanks! I have one more error that I am encountering!

I am only getting one more error. Normally I would attempt a PR for something like this but I just don't have time, and no experience with babel plugins.

Here is the error
```bash
ERROR in ./src/forms/utils/validations.js
Module build failed: TypeError: /Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/src/forms/utils/validations.js: Cannot read property 'map' of undefined
    at makePropTypesAst (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/makePropTypesAst.js:23:47)
    at PluginPass.ExportNamedDeclaration (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:86:59)
    at newFn (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:135:17)
    at Object.traverse [as default] (/Users/ericwooley/Dropbox/projects/company_name_removed/react-frontend/node_modules/babel-traverse/lib/index.js:69:12)
 @ ./src/forms/recommendation_form.js 84:19-53
```
and the file
```js
// @flow
import {genders, allStates} from './lists'
import moment from 'moment'
export type Validation = (input: string, humanReadable: string) => string|?string

export function required (): Validation {
  return (input: string, humanReadable: string): ?string => {
    if (!input) return `${humanReadable} is required`
  }
}
export function dob (minAge: ?number, maxAge: ?number): Validation {
  return (input: string, humanReadable: string): string => {
    const birthDay = moment(Date.parse(input))
    const now = moment()
    if (typeof minAge === 'number') {
      if (now.subtract(minAge, 'year').isBefore(birthDay)) {
        return `${humanReadable} must be ${minAge} years or older`
      }
    }
    if (typeof maxAge === 'number') {
      if (now.add(maxAge, 'year').isAfter(birthDay)) {
        return `${humanReadable} must be ${minAge} years or younger`
      }
    }
    return ''
  }
}
export function gender (): Validation {
  return oneOf(genders)
}

export function state () : Validation {
  return oneOf(allStates)
}

export function phoneNumber (): Validation {
  return (input: string, humanReadable: string): ?string => {
    return ''
  }
}

export function minLength (minLength: number): Validation {
  return (input: string, humanReadable: string): ?string => {
    if (input && input.length < minLength) return `${humanReadable} must be at least ${minLength} characters`
  }
}
export function maxLength (maxLength: number): Validation {
  return (input: string, humanReadable: string): string => {
    if (input && input.length > maxLength) return `${humanReadable} must be less than ${minLength} characters`
    return ''
  }
}

export function oneOf (possibleOptions: Array<string>) : Validation {
  return (input: string, humanReadable: string): ?string => {
    if (input) {
      const isInList = possibleOptions.some((value) => value === input)
      if (!isInList) return `${humanReadable} is not a valid option`
    }
  }
}

export function email (): Validation {
  return (input: string, humanReadable: string): ?string => {
    if (input && !input.match(/^[^@]+@[^@]+\.[^@]+$/)) return `${humanReadable} is malformed`
  }
}

export function website (): Validation {
  return (input: string, humanReadable: string): ?string => {
    if (input && !input.match(/[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/)) {
      return `${humanReadable} is malformed`
    }
  }
}

export function validateInput (input: string, humanReadable: string, ...validations: Array<Validation>): string | void {
  for (let i = 0; i < validations.length; i++) {
    const potentialError = validations[i](input, humanReadable)
    if (potentialError) return potentialError
  }
}
```
