### ISSUE TITLE
Support literal unions

### ISSUE THREAD

**Issue by tmc** [brigand/babel-plugin-flow-react-proptypes#19]
```
export type A = "option1" | "option2";
```

produces:

```
types.js: Cannot read property 'map' of undefined
    at makePropTypesAst (/Users/tmc/foobar/node_modules/babel-plugin-flow-react-proptypes/lib/makePropTypesAst.js:23:47)
    at PluginPass.ExportNamedDeclaration (/Users/tmc/foobar/node_modules/babel-plugin-flow-react-proptypes/lib/index.js:87:59)
    at newFn (/usr/local/lib/node_modules/babel-cli/node_modules/babel-traverse/lib/visitors.js:262:19)
```

**Comment by brigand** [comment]
Thanks for the report. This is going to take some time to fix. I'll look into it later.

**Comment by tmc** [comment]
so this works if the literal union isn't top level.

**Comment by faceyspacey** [comment]
+1

what needs to be done to get this working?

**Comment by brigand** [comment]
Currently only object types are supported at the top level. It'd require a lot of changes to the code to make this work, and for little gain unless I'm missing something.

**Comment by mhaas** [comment]
This is working now in 3.0.0; see PR #89
