### ISSUE TITLE
Encountered an unknown node in the type definition. TypeofTypeAnnotation, GenericTypeAnnotation

### ISSUE THREAD

**Issue by rosskevin** [brigand/babel-plugin-flow-react-proptypes#28]
Version 0.7.3

Flow 0.28.0 checking is successful

Type declaration ([Source](https://github.com/alienfast/material-ui/commit/f965f7f744f225072b9fac129c38f409e16e9a8d#diff-71be76acb22a53104726196bdc797ec1R38)):
```javascript
type DefaultProps = {
  modalManager: typeof modalManager,
  show: boolean,
};
```
Error:
```
ERROR in ./~/material-ui-next/src/internal/Modal.js
Module build failed: Error: /Users/kross/projects/af_core/node_modules/material-ui-next/src/internal/Modal.js: babel-plugin-flow-react-proptypes: Encountered an unknown node in the type definition. Node: {"type":"TypeofTypeAnnotation","start":1149,"end":1168,"loc":{"start":{"line":38,"column":16},"end":{"line":38,"column":35}},"argument":{"type":"GenericTypeAnnotation","start":1156,"end":1168,"loc":{"start":{"line":38,"column":23},"end":{"line":38,"column":35}},"typeParameters":null,"id":{"type":"Identifier","start":1156,"end":1168,"loc":{"start":{"line":38,"column":23},"end":{"line":38,"column":35}},"name":"modalManager"}}}
  at convertToPropTypes (/Users/kross/projects/af_core/node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:83:11)
   at /Users/kross/projects/af_core/node_modules/babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js:20:15
```

**Comment by brigand** [comment]
Wasn't aware of this. I think I'll make it be `PropTypes.any.isRequired` because we're not tracing types.

**Comment by skovhus** [comment]
I cannot reproduce this error. I think this is fixed. 

Please check @rosskevin

**Comment by rosskevin** [comment]
If it cannot be reproduced, I assume it is good. The mui team declined my PR adding flow type checking. Thank you
