### ISSUE TITLE
Crash when React Component subclass positioned in same file with stateless component

### ISSUE THREAD

**Issue by dalexand** [brigand/babel-plugin-flow-react-proptypes#42]
A transformation crashes when i tryied to compile this.

**index.js**

    import React, {Component, PropTypes} from 'react';

    type TaskGridHeaderProps = {
        tasksSetSort: any
    };

    export default class TaskGridHeader extends Component {
        props: TaskGridHeaderProps;

        render() {
            return null;
        }
    }

    const glyph = (param?: any) => (
        <div/>
    );

**.babelrc**

    {
      "presets": ["es2015", "stage-1", "react"],
      "plugins": [ "flow-react-proptypes", "transform-flow-strip-types"]
    }

**Result**

    Error: src/index.js: Expected prop types, but found none. This is a bug in babel-plugin-flow-react-proptypes
        at getPropsForTypeAnnotation (d:\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:42:11)
        at getFunctionalComponentTypeProps (d:\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:58:10)
        at functionVisitor (d:\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:137:17)
        at PluginPass.ArrowFunctionExpression (d:\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:197:16)
        at newFn (d:\test\node_modules\babel-traverse\lib\visitors.js:276:21)
        at NodePath._call (d:\test\node_modules\babel-traverse\lib\path\context.js:76:18)
        at NodePath.call (d:\test\node_modules\babel-traverse\lib\path\context.js:48:17)
        at NodePath.visit (d:\test\node_modules\babel-traverse\lib\path\context.js:105:12)
        at TraversalContext.visitQueue (d:\test\node_modules\babel-traverse\lib\context.js:150:16)
        at TraversalContext.visitSingle (d:\test\node_modules\babel-traverse\lib\context.js:108:19)
        at TraversalContext.visit (d:\test\node_modules\babel-traverse\lib\context.js:192:19)
        at Function.traverse.node (d:\test\node_modules\babel-traverse\lib\index.js:114:17)

Replacement of glyph function to this 

    const glyph = () => (
        <div/>
    );
fixed the crash.

The error presents in releases after 0.9.6 (i'm still using it therefore)

**Comment by brigand** [comment]
Thanks for the report! Published as 0.12.0.

**Comment by dalexand** [comment]
Alas, but crash still happens. This is the gist with my test data.

https://gist.github.com/dalexand/201d0f7d9e1f0346f15b70a8ec32eab8

**Comment by brigand** [comment]
@dalexand you still have 0.11 in the package.json.

**Comment by dalexand** [comment]
Sorry, it's my fault.
