### ISSUE TITLE
Issue with a file that just contains some exports

### ISSUE THREAD

**Issue by MoOx** [brigand/babel-plugin-flow-react-proptypes#7]
```js
export appcache from "./validators/appcache.js"
export assets from "./validators/assets.js"
export baseUrl from "./validators/baseUrl.js"
export production from "./validators/production.js"
```

Error

```
TypeError: src/configurator/validators.js: Cannot read property 'type' of undefined
    at PluginPass.ExportNamedDeclaration (.../babel-plugin-flow-react-proptypes/lib/index.js:64:29)
    at newFn (.../babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (.../babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (.../babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (.../babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (.../babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (.../babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (.../babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (.../babel-traverse/lib/index.js:135:17)
    at NodePath.visit (.../babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (.../babel-traverse/lib/context.js:152:16)
```

**Comment by brigand** [comment]
Thanks for reporting! Fixed in 0.3.1.
